image: ghcr.io/sushrut1101/docker:arch

variables:
  FOX_SYNC: "https://gitlab.com/OrangeFox/sync.git"
  CONFIG: "config3.sh"

OrangeFox-CI:
  stage: build
  timeout: 3 hours
  script:
    - curl -sL https://raw.githubusercontent.com/Nico170420/script/main/config.sh | bash
